# Generated by Django 4.2 on 2024-03-03 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='saved_by',
            field=models.ManyToManyField(default=list, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
