# Generated by Django 4.2 on 2024-03-03 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_saved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
