# Generated by Django 4.2 on 2024-04-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_description_alter_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='highest_bid_id',
            new_name='highest_bid',
        ),
    ]
